// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  navigationItem: string;
  navigationLink: string;
}
export const cssExports: CssExports;
export default cssExports;
