// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  copy: string;
  footer: string;
  slogan: string;
  wrapper: string;
}
export const cssExports: CssExports;
export default cssExports;
