// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'copyright': string;
  'root': string;
  'slogan': string;
  'wrapper': string;
}
export const cssExports: CssExports;
export default cssExports;
